-- MySQL Script generated by MySQL Workbench
-- Fri Feb 24 14:44:06 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`plantenlabel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plantenlabel` (
  `plantenlabel_id` INT NOT NULL,
  `naam` VARCHAR(45) NOT NULL,
  `adres` VARCHAR(45) NOT NULL,
  `telefoonnummer` INT NOT NULL,
  `email_adres` VARCHAR(45) NOT NULL,
  `plantenlabelcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`plantenlabel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`studio` (
  `studio_id` INT NOT NULL,
  `naam` VARCHAR(45) NULL,
  `adres` VARCHAR(45) NULL,
  `telefoonnummer` INT NULL,
  `email_adres` VARCHAR(45) NULL,
  PRIMARY KEY (`studio_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artiest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artiest` (
  `artiest_id` INT NOT NULL,
  `artiest_naam` VARCHAR(45) NULL,
  `voornaam` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  `adres` VARCHAR(45) NULL,
  `plantenlabel_plantenlabel_id` INT NOT NULL,
  `studio_studio_id` INT NOT NULL,
  PRIMARY KEY (`artiest_id`, `plantenlabel_plantenlabel_id`),
  INDEX `fk_artiets_plantenlabel_idx` (`plantenlabel_plantenlabel_id` ASC),
  INDEX `fk_artiets_studio1_idx` (`studio_studio_id` ASC),
  CONSTRAINT `fk_artiets_plantenlabel`
    FOREIGN KEY (`plantenlabel_plantenlabel_id`)
    REFERENCES `mydb`.`plantenlabel` (`plantenlabel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artiets_studio1`
    FOREIGN KEY (`studio_studio_id`)
    REFERENCES `mydb`.`studio` (`studio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`album` (
  `album_id` INT NOT NULL,
  `naam` VARCHAR(45) NULL,
  `genre` VARCHAR(45) NULL,
  `release_date` DATE NULL,
  `artiets_artiest_id` INT NOT NULL,
  `artiets_plantenlabel_plantenlabel_id` INT NOT NULL,
  PRIMARY KEY (`album_id`, `artiets_artiest_id`, `artiets_plantenlabel_plantenlabel_id`),
  INDEX `fk_album_artiets1_idx` (`artiets_artiest_id` ASC, `artiets_plantenlabel_plantenlabel_id` ASC),
  CONSTRAINT `fk_album_artiets1`
    FOREIGN KEY (`artiets_artiest_id` , `artiets_plantenlabel_plantenlabel_id`)
    REFERENCES `mydb`.`artiest` (`artiest_id` , `plantenlabel_plantenlabel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `genre_id` INT NOT NULL,
  `genre` VARCHAR(45) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre_has_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre_has_album` (
  `genre_genre_id` INT NOT NULL,
  `album_album_id` INT NOT NULL,
  `album_artiets_artiest_id` INT NOT NULL,
  `album_artiets_plantenlabel_plantenlabel_id` INT NOT NULL,
  PRIMARY KEY (`genre_genre_id`, `album_album_id`, `album_artiets_artiest_id`, `album_artiets_plantenlabel_plantenlabel_id`),
  INDEX `fk_genre_has_album_album1_idx` (`album_album_id` ASC, `album_artiets_artiest_id` ASC, `album_artiets_plantenlabel_plantenlabel_id` ASC),
  INDEX `fk_genre_has_album_genre1_idx` (`genre_genre_id` ASC),
  CONSTRAINT `fk_genre_has_album_genre1`
    FOREIGN KEY (`genre_genre_id`)
    REFERENCES `mydb`.`genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genre_has_album_album1`
    FOREIGN KEY (`album_album_id` , `album_artiets_artiest_id` , `album_artiets_plantenlabel_plantenlabel_id`)
    REFERENCES `mydb`.`album` (`album_id` , `artiets_artiest_id` , `artiets_plantenlabel_plantenlabel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
